### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by apexdesigns** [apexdesigns/towncontrol#14]
Filter out permissions already add to group from new permissions

**Comment by jbomhold3** [comment]
Change: Settings Groups. Now filters out permissions already use in that group. So you can no longer add the same permission twice.
Change: Settings Groups. Permissions are not toggle-able inside the permission list. You no longer have to delete a permission and read it to change it's value
Change: Settings Group. Group list is now pinned to the top well you scroll down. So you can always see the group list. No matter how long the permissions are.
Change: Settings Group. Split permissions into Area and Component. No more TownSettings/Groups. Not it's Area = Settings Component = Groups. Much more human readable
