### ISSUE TITLE
Report Builder issue

### ISSUE THREAD

**Issue by apexdesigns** [apexdesigns/towncontrol#19]
File does not show up if a town has no existing reports.

**Comment by RSilvercloud** [comment]
This is now happening with reports when a change is made. 

![apex issue](https://user-images.githubusercontent.com/40879397/43681667-7eddcf92-9828-11e8-86d2-b0699b7f4d0c.png)

It says that it reconnects, but when the report is open the changes are not made.  I know you are probably working on it, just trying to keep you updated, I guess reports didn't like the migration lol

**Comment by apexdesigns** [comment]
Increased the socket buffer size. The issue with the form your working on is resolved.
