### ISSUE TITLE
Report - Condition

### ISSUE THREAD

**Issue by ChristopheKeng** [apexdesigns/towncontrol#21]
Hello, when you are making a Report with a simple conditional (If XYZ True, then show), the Input is not saved.

https://gyazo.com/3e5981e637f518a915c8ce42da34da64

https://gyazo.com/6ac6203a52c82ba178efc3d0c2d35555

**Comment by apexdesigns** [comment]
This was a setting issue in the report it's self. It's resolved by removing and re adding the field
