### ISSUE TITLE
Templates - Color of Text

### ISSUE THREAD

**Issue by ChristopheKeng** [apexdesigns/towncontrol#22]
Hello,

changing of Textcolor not possible, only for background.

**Comment by jbomhold3** [comment]
For what?

**Comment by jbomhold3** [comment]
What template and town. I'm using this on another town already 2 in fact and its working fine.

**Comment by ChristopheKeng** [comment]
Template is "Riverlake City" and template is "Nummernschild_Neu".

**Comment by apexdesigns** [comment]
FireFox issue will address in next build
