### ISSUE TITLE
Police Tablet V3 - Notecard not modify

### ISSUE THREAD

**Issue by ChristopheKeng** [apexdesigns/towncontrol#24]
Hi, 

the Notecard of the Police Tablet is not modify. If you open it once, it was editable, you change the UUID of the Town, Save it, after that, it isn't modify... also the UUID is changing back to the orginal one.

Also take a new one -> same issue

https://gyazo.com/3979cb869dff4b99144ae6b016ebec14

**Comment by apexdesigns** [comment]
I resent it full perm... The Config is TownId=blah  for that item if its still any issue. just remove the Config in it and put your own "Config"
