### ISSUE TITLE
Possible to include

### ISSUE THREAD

**Issue by RSilvercloud** [apexdesigns/towncontrol#3]
It is possible to include the following?

~Tooltips where if you hover over an icon it tells you want it does
~A way to archive calls where they can still be searched, but won’t take up screen space after they are closed or deleted from the active screen.

Thanks in advance for considering.  These are a couple of suggestions that David and Ethan had.

**Comment by apexdesigns** [comment]
Can do both.

**Comment by apexdesigns** [comment]
Added both features
