### ISSUE TITLE
Unable to remove background color from Tag Year layer on new plate template

### ISSUE THREAD

**Issue by lupinia** [apexdesigns/towncontrol#3]
Hi!  After creating a new license plate template, and meticulously copying all of the layer settings from another template (since there's no functionality to duplicate a template), I seem to have encountered a bug in the background color for the Tag Year layer in the new license plate template.

**Actions Taken:**  Create a new plate template, select Year Tag layer, open Background Color, and set to `#FFFFFF00` (100% transparency).

**What I expect to happen:**  The license plate expiration year should have no background color.
![Apex-Issue-Plate-Year-Correct](https://user-images.githubusercontent.com/10609083/162922084-490800e3-aa6b-44db-87e0-ee434a3f13b2.PNG)

**What actually happens:**  The license plate expiration year has a glaringly bright red background color.
![Apex-Issue-Plate-Year-Wrong](https://user-images.githubusercontent.com/10609083/162922087-f2fe8d15-a7a1-48e7-a21c-4f6127178462.PNG)

I also tried setting the background color to `#FFFFFF05`, to match the template where this works correctly (the year has no background color on that template), and that still didn't resolve the issue.  I'm unable to identify any difference between the Tag Year layers on either of these templates, so I'm not sure why I can't get rid of the year background color on the new one.

**Comment by jbomhold3** [comment]
Not a bug Tag Year gets a background color based on the current year for quicker identification of invalid plates. Most states use this system RL. Renaming the layer to anything but "Year Tag" should override this behavior

**Comment by lupinia** [comment]
Ah, thank you for the clarification; it would be nice to have some control over this, or at least have it documented somewhere, but changing the name of the layer successfully overrode this behavior (I was so tired last night that I didn't even notice it was different between the two templates, oops), so thanks for the clarification!
