### ISSUE TITLE
Feature Request:  New template from existing template

### ISSUE THREAD

**Issue by lupinia** [apexdesigns/towncontrol#4]
For highly complex templates, the process of creating similar ones (for example, to have both a driver's license and a photo ID card) is prohibitively difficult.  Each layer's settings must be transcribed by hand into a text file, then re-entered into the new template, and even then, there can still be unexpectedly different behavior in the new template (as seen in #3).  This difficulty is the main reason why I haven't used Apex nearly as much as I would like to, and this has been a problem since version 3.x.

It would be greatly appreciated if there was a way to use an existing template as the basis for a new one, perhaps by adding a Copy button based on the Open button that creates a copy of the selected template and opens that (probably the more Apex-y way to do it).

**Comment by jbomhold3** [comment]
Added building now. 
### Update 4/12/2022
>* Adds: Note about layers with the name "Year Tag" adding background color automatically.
>* New feature: Copy Template. Located under the open tab. Hitting this button will clone the template and open the copy automatically.

**Comment by lupinia** [comment]
Awesome, thank you so much!  This is a HUGE help for adding new templates with consistent layouts; we now have identification cards and learner's permits for the first time!  :D
