### ISSUE TITLE
Link to Documentation From Application

### ISSUE THREAD

**Issue by lupinia** [apexdesigns/towncontrol#61]
While the official documentation is useful, it effectively doesn't exist from the perspective of a user:  There is no "help", "support", or "documentation" link of any kind from inside the app, and even the support link on the homepage is not consistently used or labeled (I did not discover until writing this message that, of the two "support" links on the Apex Designs homepage, one of them does actually go to the documentation).  

Even better would be contextual help/info links to the relevant documentation pages from whatever the user is currently looking at.

**Comment by jbomhold3** [comment]
Added to next release
