### ISSUE TITLE
Citizen Record Cannot Be Closed From Sub-Sections

### ISSUE THREAD

**Issue by lupinia** [apexdesigns/towncontrol#64]
After working through the sections of a citizen record (registrations, credentials, etc), there is no way to close the record or return to the list without returning to the main tab, which causes the Type field to reset to a blank field, which must be re-selected before the record can be saved or closed (issue #63 ).

**Comment by jbomhold3** [comment]
Added a close button to the title bar.

**Comment by lupinia** [comment]
This button doesn't fully work; it seems to close the citizen record, but doesn't change back to the main Citizens screen.  Also, it has empty parenthesis next to it, possibly a broken label?

**Comment by jbomhold3** [comment]
Can not reproduce this in firefox or chrome. Please provide steps taken to create the issue
