### ISSUE TITLE
License Plate Templates From Previous Version Do Not Print Correctly

### ISSUE THREAD

**Issue by lupinia** [apexdesigns/towncontrol#68]
While attempting to print any license plate using a template that was created using the previous version of Town Control, even after properly saving it (and even if it's a brand-new registration that wasn't part of the old database), none of the plate data appears on the plate.  The plate number is only a series of # symbols, and the expiration month and year are blank.  Attempting to edit the template provides no insight into why this is occurring or how to fix it.  

The results of a plate printed with the new system:
![Print Results](https://user-images.githubusercontent.com/10609083/85515903-a2a60800-b5cb-11ea-93ff-4b01d9c9a266.png)

The same plate printed with the old system, illustrating what it's supposed to look like:
![Correct Plate](https://user-images.githubusercontent.com/10609083/85516646-6fb04400-b5cc-11ea-85b5-b552f65438bf.png)

**Comment by jbomhold3** [comment]
[#######] sorry this one is my fault but changing this title to add all commands to docs.

**Comment by lupinia** [comment]
Confirming that this is still a problem in the current version of Town Control, and is therefore not closed.

**Comment by jbomhold3** [comment]
You have ####### the tag is [#######] , but don't worry I went back and fixed them for you.

**Comment by lupinia** [comment]
And I'm saying that, today, right now, I am still unable to print license plates in the current version of Town Control:

![Apex-Issue-Incorrect-Plate-2021](https://user-images.githubusercontent.com/10609083/111083770-788fcf80-84e5-11eb-9177-65df3bf353a8.png)

**Comment by jbomhold3** [comment]
All replaced text text starts and ends with [] as pointed out in my response to this issue. So it would be [#######] and not ####### I fixed your templates and delete my reply because I was still in the process of fixing them. All you need to do is click edit on that record and save and it will update the template

**Comment by jbomhold3** [comment]
https://gyazo.com/bb7506b08f66d9a89b17558e8bdf9cf9

**Comment by lupinia** [comment]
Ah, ok, thanks, that helps.

**Comment by jbomhold3** [comment]
Also went ahead and just quickly ran though all of them and did that for you
