### ISSUE TITLE
Suggestions for town control

### ISSUE THREAD

**Issue by Kimberly-McBlaze** [apexdesigns/towncontrol#73]
Greetings. I have a couple of suggestions to make for Town Control.

Where we customize the color for things like fonts and such, I would like to suggest adding the ability to specify a specific color via the HEX / HTML code and / or it's RGB value in addition to the existing color system, this will allow people to choose a very specific color if they know its values or color code already.

Were we add an entry for a new citizen, there should be more options for "Gender", such as "X", "Non-Binary", or preferably, the option to put in a custom entry there. In real life, some states in the US and many countries around the world already have such options.

That's all I have for now.

**Comment by jbomhold3** [comment]
Added in 5.0
