### ISSUE TITLE
[FEATURE REQUEST] Make Pages in Sidebar  permalinks

### ISSUE THREAD

**Issue by IAmNolanPerry** [apexdesigns/towncontrol#75]
So Right Now, I guess you use JS to go to a page like Dispatch, Legal and so on, so if  you try right clicking and opening links in new tab you'll get "about:blocked", and the link you click shows "javascript(void);", This isn't helpful when trying to open your stuff up for your dispatch shift or something, cause you have to open apex in each tab, instead of being able to right click and open in new tab

**Comment by jbomhold3** [comment]
This was an early design limitation of the SPA framework used. Will just work in next release but will leave this open so I can track it.

**Comment by jbomhold3** [comment]
Added in 5.0
