### ISSUE TITLE
[FEATURE REQUEST] All SLUsernames get lowercased

### ISSUE THREAD

**Issue by jacobfear** [apexdesigns/towncontrol#80]
Change Apex so that all the SL Usernames in the database are put to lowercase.
This would be implemented as when you search for a citizen the search input is put to Lowercase, and all requests to the api are put to lowercase. This way wrong capitalization of a username is not a problem. 

This would involve retroactivly changing all the SL Usernames to lower case

**Comment by jbomhold3** [comment]
V5 Dev note. All query's for the database should be case insensitive. No need to make data changes.

**Comment by jbomhold3** [comment]
added in V5
