### ISSUE TITLE
License plate number randomly changes when creating a registration with less than 7 characters

### ISSUE THREAD

**Issue by lupinia** [apexdesigns/towncontrol#82]
When adding a new Registration to a Citizen record, I try to enter a license plate number with the registration.  My town uses short license plate numbers, with only five characters per plate.

What I expect to happen:  The registration should be created with the license plate number I enter, as in all previous versions.

What actually happens:  The registration generates a random 7-character string upon saving, which overwrites the manually-entered license plate number, requiring me to go back and edit every newly-created registration after creating them (which thankfully works, otherwise this would be a completely breaking bug).

**Comment by jbomhold3** [comment]
Fix is going live now

**Comment by jbomhold3** [comment]
Fixed tested and confirm working
